### ISSUE TITLE
Performance optimization of flight

### ISSUE THREAD

**Issue by narendrans** [narendrans/sqlalchemy_dremio#8]
## Summary

Performance of queries via flight protocol is not optimal. 

## Test case

Running a query that returns 1M records. Both Dremio and the client is local.

Dataset: Samples."samples.dremio.com"."NYC-taxi-trips" (LIMIT 1000000)

**Flight: 3.375s - Execution time in Dremio: <1s
ODBC: 3.703125** 

It looks like the time is spent entirely on the client side processing even though the data has been sent from the server in less than 1 second. Could it be this? https://github.com/narendrans/sqlalchemy_dremio/blob/master/sqlalchemy_dremio/query.py#L17

Statistics:

![image](https://user-images.githubusercontent.com/2958570/97311313-9c09f480-183a-11eb-9021-a01d43f804d2.png)

Call Graph:

![flight_perf_profiler](https://user-images.githubusercontent.com/2958570/97311115-65cc7500-183a-11eb-8bc9-0512b5b15fb9.png)

**Comment by naren-dremio** [comment]
Thanks to @rymurr. It looks like converting to pandas DF is the culprit. Processing numbers is much faster compared to strings.

`SELECT passenger_count,trip_distance_mi,pickup_longitude,pickup_latitude,dropoff_longitude,fare_amount,surcharge FROM "NYC Taxi".trips limit 3000000`

Flight: 2.78125
ODBC: 11.578125

TO DO: Refactor so that pandas is not used at all.

**Comment by narendrans** [comment]
#9  WIP
